name: Cargo Release builder, packager, publisher
description: All-in-one action to build, optimise, tag, sign, and publish a Cargo-based Rust project.
branding:
  icon: 'umbrella'
  color: 'orange'
inputs:
runs:
  using: node16
  main: dist/index.js
